<a href="https://colab.research.google.com/github/IndraWaingankarEXTC/Python-learning-curve./blob/main/Assignment_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [5]:
array_1D =np.array([1,2,3,4,5])
print("1D Array:")
print(array_1D)

1D Array:
[1 2 3 4 5]


In [6]:
array_2D =np.array([[1,2,3],[4,5,6]])
print("2D Array:")
print(array_2D)

2D Array:
[[1 2 3]
 [4 5 6]]


In [7]:
array_3D =np.array([[1,2],[3,4],[5,6]])
print("3D Array:")
print(array_3D)

3D Array:
[[1 2]
 [3 4]
 [5 6]]


In [8]:
arry_1D=array_1D.reshape(5,1)
print("reshaped array_1D:")
print(arry_1D)

reshaped array_1D:
[[1]
 [2]
 [3]
 [4]
 [5]]


In [9]:
arre = np.array([[1,2,3],[4,5,6,],[7,8,9]])
print(arre)
print(arre[1:,1:3])
print(arre[1:3,:3])
print("array:",arre)
print("shape:",arre.shape)
print("size:",arre.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 6]
 [8 9]]
[[4 5 6]
 [7 8 9]]
array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
shape: (3, 3)
size: 9


In [ ]:
arry1=np.array([1,2,3,4,5])
arry2=np.array([6,7,8,9,10])
print(arry1)
print(arry2)
print("add:",arry1+arry2)
print("substract:",arry1+-arry2)
print("multiply:",arry1*arry2)
print("divide:",arry1/arry2)

[1 2 3 4 5]
[ 6  7  8  9 10]
add: [ 7  9 11 13 15]
substract: [-5 -5 -5 -5 -5]
multiply: [ 6 14 24 36 50]
divide: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [ ]:
arry3=np.array([[1,2],[3,4]])
arry4=np.array([[6,7],[8,9]])
dot=np.dot(arry3,arry4)
cross=np.cross(arry3,arry4)
print("dot product")
print(dot)
print("cross product")
print(cross)

dot product
[[22 25]
 [50 57]]
cross product
[-5 -5]


/tmp/ipykernel_1487/825810295.py:4: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  cross=np.cross(arry3,arry4)


In [ ]:
d1=([1,2,3,4,5,6,7,8,9])
d2=([9,8,7,6,5,4,3,2,1])
print(d1)
print(d2)
print("variance:",np.var(d1))
print("mean:",np.mean(d1))
print("standard deviations:",np.std(d1))
correlation=np.corrcoef(d1,d2)
print(correlation)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[9, 8, 7, 6, 5, 4, 3, 2, 1]
variance: 6.666666666666667
mean: 5.0
standard deviations: 2.581988897471611
[[ 1. -1.]
 [-1.  1.]]
